exports.Cluster = '10.112.195.101'
exports.RBACUser = "Administrator";
exports.RBACKPassword = "password";
exports.DefaultBucket = 'test_eventing'
exports.AuthPassword = ''
// exports.Buckets = ['server', 'sdk', 'mobile']
exports.Buckets = []
exports.httpListen = '127.0.0.1'
exports.httpPort = 8205
