exports.Cluster = '172.23.121.84'
exports.RBACUser = "Administrator";
exports.RBACKPassword = "password";
exports.DefaultBucket = 'test_eventing'
exports.AuthPassword = ''
// exports.Buckets = ['server', 'sdk', 'mobile']
exports.Buckets = []
exports.httpListen = '172.23.121.84'
exports.httpPort = 8205
